### ISSUE TITLE
Mining Rig Rental Rigs not updating accepted payment methods.

### ISSUE THREAD

**Issue by sfalas01** [RainbowMiner/RainbowMiner#2223]
Updating the values of "PriceCurrencies" in the MRR pool config files does not update the rigs to reflect the changes in accepted currencies.
Force-updating the Rigs does not help either.
The only way to get around this is to delete every rig and let RBM re-create them automatically

**Comment by RainbowMiner** [comment]
I'll look into it. That shouldn't be a huge change.

**Comment by RainbowMiner** [comment]
Ok. That last commit should do the trick. Just download that new [`.\Pools\MiningRigRentals.ps1` ](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/MiningRigRentals.ps1) (you can use right-click + save as) into your local `.\Pools` folder. Then RainbowMiner should detect changes to enable/disable of currencies in parameter `PayoutCurrencies`.

**Comment by sfalas01** [comment]
> 

Ok, will check it out!

**Comment by sfalas01** [comment]
The file you linked does not contain any mention of ```Payout Currencies```. Also, the available currencies are BTC/ETH/LTC/BCH (using BTC as a base pair to derive prices, I think). You included DASH which is not supported AFAIK

**Comment by RainbowMiner** [comment]
It's `PayoutCurrencies` without any blanks. The linked pool module should in fact work - but(!) - "You included DASH which is not supported AFAIK" - thank you for that. It seems I have missed the day that MRR has disabled DASH. 
So please wait a minute, until I have removed DASH from the module.

**Comment by RainbowMiner** [comment]
Done. Now DASH has been removed from the MiningRigRentals pool module: [`.\Pools\MiningRigRentals.ps1` ](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/MiningRigRentals.ps1) (you can use right-click + save as)

**Comment by sfalas01** [comment]
> 

Again, no parameter ```PayoutCurrencies``` in [.\Pools\MiningRigRentals.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/MiningRigRentals.ps1)

**Comment by RainbowMiner** [comment]
Ah!! Sorry :) Yes, in fact. That's the correct parameter.

**Comment by sfalas01** [comment]
Replaced the .ps1 file. I manually updated the rigs through the web GUI. No apparent change over the MRR website has been identified.
I had BTC/ETH and changed the .ps1 file to enable all the possible currencies. The MRR website still shows just BTC/ETH as available for payment.

**Comment by sfalas01** [comment]
> Replaced the .ps1 file. I manually updated the rigs through the web GUI. No apparent change over the MRR website has been identified. I had BTC/ETH and changed the .ps1 file to enable all the possible currencies. The MRR website still shows just BTC/ETH as available for payment.

@RainbowMiner Maybe the API does not support changing these parameters?
