### ISSUE TITLE
Sorting Monitoring Central by efficiency is broken

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#694]
I'm trying to sort Monitoring Central by efficiency to see what are the best cards for MTP. When I do this, it sorts numerically regardless of whether the value is in hashes, megahashes or kilohashes. This makes the tool worthless for finding the best cards for efficiency, although all the data is there. Please can this be fixed before Black Friday?

**Comment by RainbowMiner** [comment]
I see - I'll try to fix it asap.

**Comment by RainbowMiner** [comment]
Should be fixed, by now.

**Comment by samdave123** [comment]
![image](https://user-images.githubusercontent.com/56473344/67151280-cafe9980-f2bb-11e9-9ccf-61cd77dff4d4.png)

![image](https://user-images.githubusercontent.com/56473344/67151284-d4880180-f2bb-11e9-9e49-1db094ff46fd.png)

Still doesn't seem to be working correctly?

**Comment by RainbowMiner** [comment]
Ah, now I spotted the problem. I have cleaned-up the database a bit. It should be good, now.

**Comment by samdave123** [comment]
Still seems broken, at least for MTP?

**Comment by RainbowMiner** [comment]
Please try again. 🍭

**Comment by samdave123** [comment]
Yep seems to be fixed, thank you.
